### PR TITLE
Remove extraneous validation on services

### PR DESCRIPTION
**Pull request by embark**
There weren't even any tests that were able to cover this case

### CODE REVIEW

**Comment by embark** [comment]
@sandersch 

could we also bump and publish the version once this is in?

**Comment by nerdrew** [comment]
Looks good.

**Comment by sandersch** [comment]
Code change LGTM. Looks like the build is failing because it can't find the updated version 4.0 of the protobuf gem.

**Comment by embark** [comment]
@sandersch Sorry, removed that, we don't need the updated version now

**Comment by somethingnew2-0** [comment]
Looks good to me

**Comment by Lwillson** [comment]
LGTM

**Pull request merged**
